#!/bin/bash
echo PWD is $PWD
git push -u origin post-commit
echo 1
exit

git push -u origin post-commit
git clone -b post-test-commit post-commit

exit
a=$(sed -n 1p test.txt|awk -F"," '{print $1}')
if [[ $a = '123' ]]
do
git checkout master
git merge one
else
echo -1
if
