#!/bin/sh

#exit 0
git branch --set-upstream-to origin/pre-push
#git push --no-verify -u origin push-test:pre-push
git branch -vv
git push --no-verify
exit 2
#FILE="flag"

#if [ -f "$FILE" ];then
#echo "exist"
#exit 0
#else
#echo "no $FILE"
#touch $FILE
#git push --no-verify -u origin push-test
#exit 0
#fi

exit
a=$0
git push -u origin origin/push-test

echo $0
echo $1
echo $2

git fetch origin/push-test origin

echo fetch

exit
